#!/usr/bin/python
# coding: utf-8

import os
import os.path
import subprocess

base = '/host'
pilot_filebeat = "filebeat"
ENV_PILOT_TYPE = "PILOT_TYPE"


def umount(volume):
    subprocess.check_call('umount -l %s' % volume, shell=True)


def mount_points():
    with open('/proc/self/mountinfo', 'r') as f:
        mounts = f.read().decode('utf-8')

    points = set()
    for line in mounts.split('\n'):
        mtab = line.split()
        if len(mtab) > 1 and mtab[4].startswith(base + '/') and mtab[4].endswith('shm') and 'containers' in mtab[4]:
            points.add(mtab[4])
    return points


def cleanup():
    umounts = mount_points()
    for volume in sorted(umounts, reverse=True):
        umount(volume)


def run():
    pilot_type = os.environ.get(ENV_PILOT_TYPE)
    if pilot_filebeat == pilot_type:
        tpl_config = "/usr/share/filebeat/watchlog/filebeat.tpl"

    os.execve('/usr/share/filebeat/watchlog/watchlog', ['/usr/share/filebeat/watchlog/watchlog', '-template', tpl_config],
              os.environ)


def config():
    pilot_type = os.environ.get(ENV_PILOT_TYPE)
    if pilot_filebeat == pilot_type:
        print "start log-pilot:", pilot_filebeat
        subprocess.check_call(['/usr/share/filebeat/watchlog/config.filebeat'])


if __name__ == '__main__':
    config()
    cleanup()
    run()