apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - env:
            # 配置日志采集前缀标志 watchlog_{xxx}
            - name: watchlog_default-nginx
              value: stdout
          image: nginx:1.18.0
          imagePullPolicy: IfNotPresent
          name: nginx
          resources: {}